# Generated by Django 3.2.3 on 2021-06-03 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15, verbose_name='IP прокси')),
                ('port', models.IntegerField(verbose_name='Порт прокси')),
                ('login', models.TextField(verbose_name='Логин от прокси сервера')),
                ('password', models.TextField(verbose_name='Пароль от прокси сервера')),
                ('datetime_last_used', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего использования аккаунта')),
                ('active', models.BooleanField(default=True, verbose_name='Статус не заблокирован ли прокси')),
            ],
            options={
                'verbose_name': 'Прокси',
                'verbose_name_plural': 'Прокси',
                'ordering': ('datetime_last_used',),
            },
        ),
        migrations.CreateModel(
            name='YandexAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=100, verbose_name='Логин')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('count_captcha', models.IntegerField(blank=True, default=0, null=True, verbose_name='Количество появлений каптч')),
                ('active', models.BooleanField(default=True, verbose_name='Статус не заблокирован ли аккаунт')),
                ('datetime_last_used', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего использования аккаунта')),
            ],
            options={
                'verbose_name': 'Яндекс аккаунт',
                'verbose_name_plural': 'Яндекс аккаунты',
                'ordering': ('datetime_last_used',),
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_last_used', models.DateTimeField(auto_now=True, null=True, verbose_name='Время последнего использования аккаунта')),
                ('is_used', models.BooleanField(default=False, verbose_name='Статус используется ли сессия')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordstat.yandexaccount')),
                ('proxy', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='wordstat.proxy')),
            ],
            options={
                'verbose_name': 'Сессия',
                'verbose_name_plural': 'Сессии',
            },
        ),
    ]