# Generated by Django 3.2.4 on 2021-06-04 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordstat', '0002_auto_20210602_1406'),
        ('wordstat', '0003_auto_20210603_1558'),
    ]

    operations = [
    ]
